[package]
name = "embedded_dhcp_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
dbg =[]
[dependencies]

[dev-dependencies]
rand="0.8.5"